name = "skify-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# Run: wrangler d1 create skify-db
# Then paste the database_id below
[[d1_databases]]
binding = "DB"
database_name = "skify-db"
database_id = "952f6c35-56a4-40df-ac8f-d375a42d2ced"

[[r2_buckets]]
binding = "SKILLS"
bucket_name = "skify-storage"

[vars]
GITHUB_API = "https://api.github.com"
